; Automatically generated by SBV. Do not edit.
(set-option :print-success true)
(set-option :global-declarations true)
(set-option :smtlib2_compliant true)
(set-option :produce-models true)
(set-option :pp.bv-literals false)
(set-logic QF_FPBV)
; --- tuples ---
; --- sums ---
; --- literal constants ---
(define-fun s1 () RoundingMode roundNearestTiesToEven)
(define-fun s2 () (_ BitVec 32) #x4a211526)
(define-fun s4 () (_ BitVec 32) #x00000000)
(define-fun s6 () (_ BitVec 32) #x00000001)
(define-fun s8 () (_ BitVec 32) (bvneg #x00000001))
(define-fun s17 () (_ BitVec 64) #x000000000dd04f97)
(define-fun s19 () (_ BitVec 32) #x0000003a)
(define-fun s23 () (_ BitVec 32) #x0000001f)
; --- top level inputs ---
(declare-fun s0 () (_ BitVec 32)) ; tracks user variable "parm10"
; --- constant tables ---
; --- non-constant tables ---
; --- uninterpreted constants ---
; --- user defined functions ---
; --- assignments ---
(define-fun s3 () (_ BitVec 32) (bvsrem s0 s2))
(define-fun s5 () Bool (bvsgt s3 s4))
(define-fun s7 () Bool (bvslt s3 s4))
(define-fun s9 () (_ BitVec 32) (ite s7 s8 s3))
(define-fun s10 () (_ BitVec 32) (ite s5 s6 s9))
(define-fun s11 () Bool (= s8 s10))
(define-fun s12 () (_ BitVec 32) (bvsdiv s0 s2))
(define-fun s13 () (_ BitVec 32) (bvsub s12 s6))
(define-fun s14 () (_ BitVec 32) (ite s11 s13 s12))
(define-fun s15 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) s1 s14))
(define-fun s16 () (_ BitVec 64) ((_ sign_extend 32) s0))
(define-fun s18 () (_ BitVec 64) (bvmul s16 s17))
(define-fun s20 () (_ BitVec 64) ((_ sign_extend 32) s19))
(define-fun s21 () (_ BitVec 64) (bvashr s18 s20))
(define-fun s22 () (_ BitVec 32) ((_ extract 31 0) s21))
(define-fun s24 () (_ BitVec 32) (bvashr s0 s23))
(define-fun s25 () (_ BitVec 32) (bvsub s22 s24))
(define-fun s26 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) s1 s25))
(define-fun s27 () Bool (= s15 s26))
(define-fun s28 () Bool (not s27))
; --- delayedEqualities ---
; --- formula ---
(assert s28)
(check-sat)
(get-value (s0))
(get-value (s3))
(get-value (s15))
(get-value (s26))
